/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package funcionario;

import database.DBWorker;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rui Oliveira
 */
public class JFrameInserirFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form JFrameInserirFuncionario
     */
    public JFrameInserirFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFuncID = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtEspecialidade = new javax.swing.JTextField();
        txtTelemovel = new javax.swing.JTextField();
        chkCartaConducao = new javax.swing.JCheckBox();
        btnAdicionaFunc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtFuncID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFuncID.setText("Insere id aqui...");
        txtFuncID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFuncIDMouseClicked(evt);
            }
        });
        txtFuncID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncIDActionPerformed(evt);
            }
        });

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNome.setText("Insere o nome aqui...");
        txtNome.setToolTipText("");
        txtNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomeMouseClicked(evt);
            }
        });

        txtEspecialidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEspecialidade.setText("Insere a especialidade aqui...");
        txtEspecialidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEspecialidadeMouseClicked(evt);
            }
        });

        txtTelemovel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTelemovel.setText("Insere telemovel aqui....");
        txtTelemovel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTelemovelMouseClicked(evt);
            }
        });

        chkCartaConducao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkCartaConducao.setText("Carta Conducao");

        btnAdicionaFunc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdicionaFunc.setText("Submeter");
        btnAdicionaFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionaFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFuncID)
                    .addComponent(txtNome)
                    .addComponent(txtEspecialidade)
                    .addComponent(txtTelemovel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkCartaConducao)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btnAdicionaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFuncID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTelemovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkCartaConducao)
                .addGap(18, 18, 18)
                .addComponent(btnAdicionaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFuncIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuncIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuncIDActionPerformed

    private void btnAdicionaFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionaFuncActionPerformed
        try {
            // TODO add your handling code here:
            DBWorker db = new DBWorker("127.0.0.1", "root", "", "gice");
            int funcID = Integer.parseInt(txtFuncID.getText());
            String nome = txtNome.getText();
            String especialidade = txtEspecialidade.getText();
            int telemovel = Integer.parseInt(txtTelemovel.getText());
            String cartaConducao = "";
            if(chkCartaConducao.isSelected()) {
                cartaConducao = "Sim";
            } else if(!chkCartaConducao.isSelected()) {
                cartaConducao = "Nao";
            }
            String sqlCode = "INSERT INTO funcionarios(funcID,nome,especialidade,telemovel,carta_conducao) VALUES('" + funcID + "','" + nome + "','" + especialidade + "','" + telemovel + "','" + cartaConducao + "');";
            
            
            if(nome.isEmpty() == false && especialidade.isEmpty() == false && funcID != 0 && telemovel != 0) {
                db.executeUpdate(sqlCode);
                this.dispose();
            }
            
        } catch (SQLException | ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
            Logger.getLogger(JFrameInserirFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnAdicionaFuncActionPerformed

    private void txtFuncIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFuncIDMouseClicked
        // TODO add your handling code here:
        txtFuncID.setText("");
    }//GEN-LAST:event_txtFuncIDMouseClicked

    private void txtNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomeMouseClicked
        // TODO add your handling code here:
        txtNome.setText("");
    }//GEN-LAST:event_txtNomeMouseClicked

    private void txtEspecialidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEspecialidadeMouseClicked
        // TODO add your handling code here:
        txtEspecialidade.setText("");
    }//GEN-LAST:event_txtEspecialidadeMouseClicked

    private void txtTelemovelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelemovelMouseClicked
        // TODO add your handling code here:
        txtTelemovel.setText("");
    }//GEN-LAST:event_txtTelemovelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameInserirFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameInserirFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameInserirFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameInserirFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameInserirFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionaFunc;
    private javax.swing.JCheckBox chkCartaConducao;
    private javax.swing.JTextField txtEspecialidade;
    private javax.swing.JTextField txtFuncID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelemovel;
    // End of variables declaration//GEN-END:variables
}
