/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package core;

import database.DBWorker;
import funcionario.JFrameEditarFuncionario;
import funcionario.JFrameInserirFuncionario;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.ResultSetTableModel;

/**
 *
 * @author Rui Oliveira
 */
public class JFrameFuncionario extends javax.swing.JFrame {

    private DBWorker dbWorker;
    private ResultSetTableModel defaultTable;
    /**
     * Creates new form JFrameFuncionario
     */
    public JFrameFuncionario() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        try {
            String servidor = "127.0.0.1";
            String user = "root";
            String password = "";
            String baseDados = "gice";
            
            dbWorker = new DBWorker(servidor, user, password, baseDados);
            ResultSet rs = dbWorker.executeQuery("SELECT * FROM funcionarios");
            defaultTable = new ResultSetTableModel(rs);
            jTableFuncionario.setModel(defaultTable);
        } catch (SQLException | ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
            Logger.getLogger(JFrameFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFuncionario = new javax.swing.JTable();
        btnInserirFunc = new javax.swing.JButton();
        btnRemoverFunc = new javax.swing.JButton();
        btnEditarFunc = new javax.swing.JButton();
        btnListarFunc = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTableFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableFuncionario);

        btnInserirFunc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnInserirFunc.setText("Adicionar");
        btnInserirFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirFuncActionPerformed(evt);
            }
        });

        btnRemoverFunc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRemoverFunc.setText("Remover");
        btnRemoverFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverFuncActionPerformed(evt);
            }
        });

        btnEditarFunc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditarFunc.setText("Alterar");
        btnEditarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarFuncActionPerformed(evt);
            }
        });

        btnListarFunc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnListarFunc.setText("Listar");
        btnListarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarFuncActionPerformed(evt);
            }
        });

        jMenu1.setText("Principal");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cliente");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInserirFunc)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoverFunc)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarFunc)
                        .addGap(18, 18, 18)
                        .addComponent(btnListarFunc)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserirFunc)
                    .addComponent(btnRemoverFunc)
                    .addComponent(btnEditarFunc)
                    .addComponent(btnListarFunc))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirFuncActionPerformed
        // TODO add your handling code here:
        JFrameInserirFuncionario funcIn = new JFrameInserirFuncionario();
        funcIn.setLocation(this.getLocation().x,this.getLocation().y);
        funcIn.setVisible(true);
    }//GEN-LAST:event_btnInserirFuncActionPerformed

    private void btnRemoverFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverFuncActionPerformed
        try {
            // TODO add your handling code here:
            int index = jTableFuncionario.getSelectedRow();
            int indexID = Integer.parseInt(defaultTable.getValueAt(index, 0).toString());
            
            RemoverLinhaTarefa(indexID);
            
            String remover = "DELETE FROM funcionarios WHERE funcID = " + indexID + ";";
            dbWorker.executeUpdate(remover);
            
            ResultSet rs = dbWorker.executeQuery("SELECT * FROM funcionarios");
            ResultSetTableModel dTable = new ResultSetTableModel(rs);
            jTableFuncionario.setModel(dTable);
        } catch (SQLException ex) {
            Logger.getLogger(JFrameFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRemoverFuncActionPerformed

    private void RemoverLinhaTarefa(int pk) {
        try {
            String remove = "DELETE FROM linhatarefas WHERE funcionarioID = " + pk + ";";
            dbWorker.executeUpdate(remove);
        } catch (SQLException ex) {
            Logger.getLogger(JFrameFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnEditarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarFuncActionPerformed
        
        int index = jTableFuncionario.getSelectedRow();
        int indexID = Integer.parseInt(jTableFuncionario.getValueAt(index, 0).toString());
        
        JFrameEditarFuncionario edFunc = new JFrameEditarFuncionario();
        edFunc.txtFuncID.setText(jTableFuncionario.getValueAt(index, 0).toString());
        edFunc.txtNome.setText(jTableFuncionario.getValueAt(index, 1).toString());
        edFunc.txtEspecialidade.setText(jTableFuncionario.getValueAt(index, 2).toString());
        edFunc.txtTelemovel.setText(jTableFuncionario.getValueAt(index, 3).toString());
        edFunc.funcionarioID = indexID;
        edFunc.setLocation(this.getLocation().x,this.getLocation().y);
        edFunc.setVisible(true);
    }//GEN-LAST:event_btnEditarFuncActionPerformed

    private void btnListarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarFuncActionPerformed
        try {
            // TODO add your handling code here:
            String servidor = "127.0.0.1";
            String user = "root";
            String password = "";
            String baseDados = "gice";
            
            dbWorker = new DBWorker(servidor, user, password, baseDados);
            ResultSet rs = dbWorker.executeQuery("SELECT * FROM funcionarios");
            defaultTable = new ResultSetTableModel(rs);
            jTableFuncionario.setModel(defaultTable);
        } catch (SQLException | ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
            Logger.getLogger(JFrameFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnListarFuncActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        JFramePrincipal jP = new JFramePrincipal();
        jP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        JFrameCliente c = new JFrameCliente();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarFunc;
    private javax.swing.JButton btnInserirFunc;
    private javax.swing.JButton btnListarFunc;
    private javax.swing.JButton btnRemoverFunc;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFuncionario;
    // End of variables declaration//GEN-END:variables
}
