/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package core;

import com.github.lgooddatepicker.components.DatePickerSettings;
import database.DBWorker;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JOptionPane;
import model.ResultSetTableModel;
import model.SimpleAudioPlayer;
import tarefas.JFrameInserirTarefa;
import tarefas.RecTarefas;

/**
 *
 * @author Admin
 */
public class JFramePrincipal extends javax.swing.JFrame {

    private DBWorker dbWorker;
    private ResultSetTableModel defaultTable;
    private DatePickerSettings dateSettings;
    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
        
        //Teste de audio
//        try {
////             SimpleAudioPlayer.filePath = "D:/Projeto p/ProjetoICE/beep_warning.wav"; 
////             SimpleAudioPlayer audioPlayer;
////             audioPlayer = new SimpleAudioPlayer();
//             //audioPlayer.play();
//        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
//            Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
//        }
              
         
        //Meter formulario no centro do ecra
        this.pack();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        //Defenicoes por defeito do componente 
        dateSettings = new DatePickerSettings();
        dateSettings.setFormatForDatesCommonEra("yyyy-MM-dd");
        datePicker1.setSettings(dateSettings);
        dateSettings = new DatePickerSettings();
        dateSettings.setFormatForDatesCommonEra("yyyy-MM-dd");
        datePicker2.setSettings(dateSettings);
        
        
        try {
            //Conectar á base de dados
            String servidor = "127.0.0.1";
            String user = "root";
            String password = "";
            String baseDados = "gice";
            dbWorker = new DBWorker(servidor, user, password, baseDados);
            
            //Listar as tarefas na instancia deste formulario
            ResultSet rs = dbWorker.executeQuery("SELECT * FROM tarefas;");
            defaultTable = new ResultSetTableModel(rs);
            jTableTarefas.setModel(defaultTable);
            
            //Listar as linhas de tarefas na instancia deste formulario
            ResultSet lnRS = dbWorker.executeQuery("SELECT * FROM linhatarefas;");
            defaultTable = new ResultSetTableModel(lnRS);
            jTableLinhaTarefas.setModel(defaultTable);
            
        } catch (SQLException | ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
            Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLinhaTarefas = new javax.swing.JTable();
        btnRecolonizarLT = new javax.swing.JButton();
        txtEspecialidade = new javax.swing.JTextField();
        btnEncontrarPorEspecialidade = new javax.swing.JButton();
        btnCartaConducao = new javax.swing.JButton();
        btnListarLinhaTarefas = new javax.swing.JButton();
        btnSemCarta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTarefas = new javax.swing.JTable();
        btnRecolonizarTarefas = new javax.swing.JButton();
        btnListarTarefasPorTerminar = new javax.swing.JButton();
        btnListarEntreDatas = new javax.swing.JButton();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        datePicker2 = new com.github.lgooddatepicker.components.DatePicker();
        btnAdicionarTarefa = new javax.swing.JButton();
        btnAtualizarTarefas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCliente = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTableLinhaTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableLinhaTarefas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableLinhaTarefasKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableLinhaTarefas);

        btnRecolonizarLT.setText("Recolonizar Linha de Tarefas");
        btnRecolonizarLT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRecolonizarLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecolonizarLTActionPerformed(evt);
            }
        });

        txtEspecialidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnEncontrarPorEspecialidade.setText("Encontrar por Especialidade");
        btnEncontrarPorEspecialidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEncontrarPorEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncontrarPorEspecialidadeActionPerformed(evt);
            }
        });

        btnCartaConducao.setText("Listar com carta conducao");
        btnCartaConducao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCartaConducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartaConducaoActionPerformed(evt);
            }
        });

        btnListarLinhaTarefas.setText("Atualizar Tabela");
        btnListarLinhaTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarLinhaTarefasActionPerformed(evt);
            }
        });

        btnSemCarta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSemCarta.setText("Listar sem carta conducao");
        btnSemCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSemCartaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRecolonizarLT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEncontrarPorEspecialidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCartaConducao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSemCarta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListarLinhaTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEncontrarPorEspecialidade, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                    .addComponent(btnRecolonizarLT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListarLinhaTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCartaConducao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSemCarta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("LinhaTarefas", jPanel1);

        jTableTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableTarefas);

        btnRecolonizarTarefas.setText("RecolonizarTarefas");
        btnRecolonizarTarefas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRecolonizarTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecolonizarTarefasActionPerformed(evt);
            }
        });

        btnListarTarefasPorTerminar.setText("Tarefas por terminar");
        btnListarTarefasPorTerminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnListarTarefasPorTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarTarefasPorTerminarActionPerformed(evt);
            }
        });

        btnListarEntreDatas.setText("Entre Datas");
        btnListarEntreDatas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnListarEntreDatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarEntreDatasActionPerformed(evt);
            }
        });

        btnAdicionarTarefa.setText("Adicionar Tarefa");
        btnAdicionarTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarTarefaActionPerformed(evt);
            }
        });

        btnAtualizarTarefas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAtualizarTarefas.setText("Atualizar Tabela");
        btnAtualizarTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarTarefasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAdicionarTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRecolonizarTarefas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListarTarefasPorTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListarEntreDatas, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datePicker2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(btnAtualizarTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(datePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdicionarTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRecolonizarTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnListarTarefasPorTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnListarEntreDatas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizarTarefas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Tarefas", jPanel2);

        jMenuCliente.setText("Cliente");
        jMenuCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuClienteMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuCliente);

        jMenu2.setText("Funcionario");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuClienteMouseClicked
        //Instanciacao de um frame para manejar clientes
        JFrameCliente c = new JFrameCliente();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuClienteMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        //Instanciacao de um frame para manejar funcionarios
        JFrameFuncionario f = new JFrameFuncionario();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void btnRecolonizarTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecolonizarTarefasActionPerformed
        try {
            //Recolonizacao das tarefas
            RecTarefas rec = new RecTarefas();
            rec.RecolonizarTarefas();
            
            //Atualizacao da tabela das tarefas
            String sql = "SELECT * FROM tarefas;";
            ResultSet rs = dbWorker.executeQuery(sql);
            defaultTable = new ResultSetTableModel(rs);
            jTableTarefas.setModel(defaultTable);
        } catch (SQLException ex) {
            Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRecolonizarTarefasActionPerformed

    private void btnListarTarefasPorTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarTarefasPorTerminarActionPerformed
        try {
            //Listar tarefas por terminar 
            String sqlCode = "SELECT * FROM tarefas WHERE estado = 'desenvolver';";
            ResultSet rs = dbWorker.executeQuery(sqlCode);
            defaultTable = new ResultSetTableModel(rs);
            jTableTarefas.setModel(defaultTable);
        } catch (SQLException ex) {
            Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListarTarefasPorTerminarActionPerformed

    private void btnListarEntreDatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarEntreDatasActionPerformed
        try {
            //Inicializacao de 2 variaveis com a data que escolheu
            String date1 = datePicker1.getText();
            String date2 = datePicker2.getText();
            
            //Listar as tarefas que estao entre as datas 
            String sqlCode = "SELECT * FROM tarefas WHERE DATE(data_inicio) BETWEEN '" + date1 + "' AND '" + date2 + "';";
            ResultSet rs = dbWorker.executeQuery(sqlCode);
            defaultTable = new ResultSetTableModel(rs);
            jTableTarefas.setModel(defaultTable);
        } catch (SQLException ex) {
            Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListarEntreDatasActionPerformed

    private void btnRecolonizarLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecolonizarLTActionPerformed
        try {
            //Recolonizacao das linhas de tarefas
            RecTarefas rec = new RecTarefas();
            rec.RecolonizarLinhaTarefas();
            
            //Atualizacao da tabela das llinhas de tarefas
            String sql = "SELECT * FROM linhatarefas;";
            ResultSet rs = dbWorker.executeQuery(sql);
            defaultTable = new ResultSetTableModel(rs);
            jTableLinhaTarefas.setModel(defaultTable);
        } catch (SQLException ex) {
            Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRecolonizarLTActionPerformed

    private void btnEncontrarPorEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncontrarPorEspecialidadeActionPerformed
        try {
            //Inicializacao de uma variavel
            String especialidade = txtEspecialidade.getText();
            
            //Listagem de linhas de tarefas que tem funcionarios com a especialidade especificada da variavel anterior
            String sqlCode = "SELECT linhatarefas.*, funcionarios.especialidade "
                    + "FROM linhatarefas INNER JOIN funcionarios ON linhatarefas.funcionarioID = funcionarios.funcID "
                    + "WHERE funcionarios.especialidade like '%" + especialidade + "%';";
            ResultSet rs = dbWorker.executeQuery(sqlCode);
            ResultSetTableModel rsM = new ResultSetTableModel(rs);
            jTableLinhaTarefas.setModel(rsM);
        } catch (SQLException ex) {
            Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnEncontrarPorEspecialidadeActionPerformed

    private void btnCartaConducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartaConducaoActionPerformed
        try {
            //Listar na tabela as linhas de tarefas onde tem funcionario com carta de conducao
            String cartaSQL = "SELECT linhatarefas.*, funcionarios.nome, funcionarios.carta_conducao "
                            + "FROM linhatarefas INNER JOIN funcionarios ON linhatarefas.funcionarioID = funcionarios.funcID "
                            + "WHERE funcionarios.carta_conducao = \"Sim\";";
            ResultSet rS = dbWorker.executeQuery(cartaSQL);
            ResultSetTableModel rsM = new ResultSetTableModel(rS);
            jTableLinhaTarefas.setModel(rsM);
        } catch (SQLException ex) {
            Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCartaConducaoActionPerformed

    private void jTableLinhaTarefasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableLinhaTarefasKeyPressed
        //Ao clicar no botao de Delete, elimina uma Linha de Tarefa
        //
        //Verificacao do evento que clicou na teclada delete
        if(evt.getKeyCode() == KeyEvent.VK_DELETE) {
            int numlinha = jTableLinhaTarefas.getSelectedRow();
            //Verificacao que selecionou um registo
            if(numlinha != -1) {
                //Inicializacao das opcoes que aparecem na caixa de dialogo
                Object[] opcoes = { "Sim", "Nao" };
                //Mensagem quue aparace na caixa de dialogo
                String str = "Confirma que quer eliminar?";
                //Caixa de dialogo
                int resultado;
                resultado = JOptionPane.showOptionDialog(rootPane, str, "Atencao", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcoes ,opcoes[1]);
                
                //Verificacao se aceitou, ou seja, clicou na opcao de "Sim"
                if(resultado == JOptionPane.YES_OPTION) {
                    try {
                        int index = jTableLinhaTarefas.getSelectedRow();
                        //Inicializar uma variavel com o valor da chave primaria que selecionou da tabela
                        String primaryKey = jTableLinhaTarefas.getValueAt(index, 0).toString();
                        
                        //Elminicao da linha de tarefa
                        String sqlCode = "DELETE FROM linhatarefas WHERE lntarefaID = '" + primaryKey + "';";
                        dbWorker.executeUpdate(sqlCode);
                        
                        //Atualizacao da tabela das linhas de tarefas
                        ResultSet rs = dbWorker.executeQuery("SELECT * FROM linhatarefas;");
                        defaultTable = new ResultSetTableModel(rs);
                        jTableLinhaTarefas.setModel(defaultTable);
                    } catch (SQLException ex) {
                        Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
            
            }
            
        }
    }//GEN-LAST:event_jTableLinhaTarefasKeyPressed

    private void btnAdicionarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarTarefaActionPerformed
        //Instanciar uma frame para adicionar tarefa
        JFrameInserirTarefa t = new JFrameInserirTarefa();
        //Quando é instanciada, aparece no local deste formulario
        t.setLocation(this.getLocation().x, this.getLocation().y);
        t.setVisible(true);
    }//GEN-LAST:event_btnAdicionarTarefaActionPerformed

    private void btnListarLinhaTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarLinhaTarefasActionPerformed
        try {
            //Atualizar a tabela das linhas de tarefas
            String sql = "SELECT * FROM linhatarefas;";
            ResultSet lnRS = dbWorker.executeQuery(sql);
            defaultTable = new ResultSetTableModel(lnRS);
            jTableLinhaTarefas.setModel(defaultTable);
        } catch (SQLException ex) {
            Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListarLinhaTarefasActionPerformed

    private void btnAtualizarTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarTarefasActionPerformed
        try {
            //Atualizar a tabela das tarefas
            ResultSet rs = dbWorker.executeQuery("SELECT * FROM tarefas;");
            defaultTable = new ResultSetTableModel(rs);
            jTableTarefas.setModel(defaultTable);
        } catch (SQLException ex) {
            Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAtualizarTarefasActionPerformed

    private void btnSemCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSemCartaActionPerformed
        try {
            //Listar na tabela as linhas de tarefas onde tem funcionario sem carta de conducao
            String cartaSQL = "SELECT linhatarefas.*, funcionarios.nome, funcionarios.carta_conducao "
                    + "FROM linhatarefas INNER JOIN funcionarios ON linhatarefas.funcionarioID = funcionarios.funcID "
                    + "WHERE funcionarios.carta_conducao = \"Nao\";";
            ResultSet rS = dbWorker.executeQuery(cartaSQL);
            defaultTable = new ResultSetTableModel(rS);
            jTableLinhaTarefas.setModel(defaultTable);
        } catch (SQLException ex) {
            Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSemCartaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarTarefa;
    private javax.swing.JButton btnAtualizarTarefas;
    private javax.swing.JButton btnCartaConducao;
    private javax.swing.JButton btnEncontrarPorEspecialidade;
    private javax.swing.JButton btnListarEntreDatas;
    private javax.swing.JButton btnListarLinhaTarefas;
    private javax.swing.JButton btnListarTarefasPorTerminar;
    private javax.swing.JButton btnRecolonizarLT;
    private javax.swing.JButton btnRecolonizarTarefas;
    private javax.swing.JButton btnSemCarta;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private com.github.lgooddatepicker.components.DatePicker datePicker2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableLinhaTarefas;
    private javax.swing.JTable jTableTarefas;
    private javax.swing.JTextField txtEspecialidade;
    // End of variables declaration//GEN-END:variables
}
